article/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('article/<str:slug>', views.detail, name = 'detail'),
    path('create-post', views.createPost, name = 'create'),
    path('article/update/<str:slug>', views.editPost, name = 'edit'),
    path('article/delete/<str:slug>', views.deletePost, name = 'delete'),
    path('category/<str:slug>', views.tagPage, name = 'tag'),
]

medium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('writer/', include('writer.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
import uuid
from django.utils import timezone
from datetime import datetime
from ckeditor.fields import RichTextField 
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from django.utils.text import slugify
from writer.models import Profile

# Create your models here.
class Post(models.Model):
    writer = models.ForeignKey(Profile, on_delete = models.SET_NULL, null = True, blank = True)
    title = models.CharField(max_length=500)
    image  = models.ImageField(upload_to='img', default='img/default.jpg')
    body = RichTextField()
    slug = models.SlugField(unique=True)
    post_id = models.UUIDField(default = uuid.uuid4, unique=True, editable = False, primary_key = True)
    tag = models.ForeignKey('Tag', on_delete = models.SET_NULL, blank = True, null = True)
    created = models.DateTimeField(auto_now_add = True)
    modified = models.DateTimeField(auto_now = True)

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length = 500)
    slug = models.SlugField()
    tag_id = models.UUIDField(default = uuid.uuid4, unique=True, editable = False, primary_key = True)
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    id = models.UUIDField(default = uuid.uuid4, unique=True, editable = False, primary_key = True)

    def __str__(self):
        return self.body

article/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Tag, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['writer','slug']



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['post',]

article/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.utils.text import slugify
from writer.models import Profile
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
def index(request):
    posts = Post.objects.all()
    page = request.GET.get('page')
    numbers = 3
    paginator = Paginator(posts, numbers)

    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        page = 1
        posts = paginator.page(page)
    
    except EmptyPage:
        page = paginator.num_pages
        posts = paginator.page(page)
    tags = Tag.objects.all()
    context = {'posts': posts, 'paginator': paginator, 'tags': tags}
    return render(request, 'article/index.html', context)


  
def detail(request, slug):
    post = Post.objects.get(slug=slug)
    posts = Post.objects.exclude(post_id__exact=post.post_id)[:5]
    form = CommentForm()
    if request.method=='POST':
        # check whether the user is login or not to comment 
            if request.user.is_authenticated:
                form = CommentForm(request.POST)
                if form.is_valid():
                    comment = form.save(commit=False)
                    comment.post = post
                    comment.save()
                    return redirect('detail', slug=post.slug)
            else:
                return redirect('signin')
    context = {'post': post, 'posts':posts, 'form': form}
    return render(request, 'article/detail.html', context)



def createPost(request):
    profile = request.user.profile
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = profile
            post.slug = slugify(post.title)
            post.save()
            messages.success(request, 'Your article was created successfully')
            return redirect('account')
    context = {'form': form}
    return render(request, 'article/create.html', context)

def editPost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)
    if request.method=='POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post updated successfully')
            return redirect('detail', slug=post.slug)
    context = {'form': form}
    return render(request, 'article/create.html', context)


def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)
    if request.method=='POST':
        post.delete()
        messages.info(request, 'Post deleted successfully')
        return redirect('account')
    context = {'form': form}
    return render(request, 'article/delete.html', context)

def followers(request, pk):
    profile = Profile.objects.get(id=pk)
    follower = request.user.profile
    return redirect(detail, pk = profile.id)

def tagPage(request, slug):
    tag = Tag.objects.get(slug=slug)
    context = {'tag': tag}
    return render(request, 'article/tag.html', context)






    

article/templates/article/create.html
{% extends 'base.html' %}

{% block content %}
<style>
   
      #cke_id_body{
        width: 100% !important;
      }
    #container{
        width: 50%;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        height: auto;
        padding: 30px 20px 20px 20px;
        border-radius: 30px;
        margin-bottom: 20px;
    }
    #container h3{
        text-align: center;
    }

    @media (max-width: 1000px){
      #container{
        width: 70%;
        padding: 20px 20px 20px 20px;
        height: auto;
        margin: auto;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        margin-top: 20px;
        margin-bottom: 20px;
  
    }
     }
   @media (max-width: 700px){
    #container{
      width: 80%;
      padding: 20px 20px 20px 20px;
      height: auto;
      margin: auto;
      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
      margin-top: 20px;
      margin-bottom: 20px;

  }
   }
   
</style>

<br><br>
<div class = 'container' id = 'container'>

<h3><strong>Create An Article</strong></h3>
<form method="POST" 
enctype="multipart/form-data" class="form-group">
{% csrf_token %}
<!-- {% for field in form %}
    <div class="form mb-3">
        <label for="floatingInput"><strong>{{field.label}}</strong></label>
        {{field}}
        
      </div>
      
      {% endfor %}
       -->
        {{form.media}}
       {{form.as_p}}
      <!-- <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
      </div> -->

      <input type = 'submit' class = 'btn btn-primary' style = 'width: 100%' value = 'Create'>

    </form>

</div>



<script>

    let inputs = document.getElementsByTagName('input')
    let textarea = document.getElementById('id_body')
    let selectTag = document.getElementById('id_tag')
    for(let i = 0; i < inputs.length; i++){
        inputs[i].classList.add('form-control')
        inputs[i].style.marginBottom = '10px'
    }
    textarea.classList.add('form-control')
    textarea.setAttribute('rows', 7)
    selectTag.classList.add('form-select')

   
</script>

{% endblock %}

article/templates/article/delete.html
{% extends 'base.html' %}

{% block content %}
<style>

    
    #cke_id_body{
        width: 100% !important;
      }
    #container{
        width: 50%;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        height: auto;
        padding: 30px 20px 20px 20px;
        border-radius: 30px;
        margin-bottom: 20px;
    }
    #container h3{
        text-align: center;
    }
   
</style>

<br><br>
<div class = 'container' id = 'container'>

<h3><strong>Delete Article</strong></h3>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.media}}
       {{form.as_p}}
      <!-- <br> -->
      
      
      <!-- <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
      </div> -->

      <input type = 'submit' class = 'btn btn-danger' style = 'width: 100%' value = 'Delete'>

    </form>

</div>



<script>

    let inputs = document.getElementsByTagName('input')
    let textarea = document.getElementById('id_body')
    let selectTag = document.getElementById('id_tag')
    for(let i = 0; i < inputs.length; i++){
        inputs[i].classList.add('form-control')
    }
    textarea.classList.add('form-control')
    textarea.setAttribute('rows', 7)
    
    selectTag.classList.add('form-select')
</script>

{% endblock %}

article/templates/article/detail.html
{% extends 'base.html' %}
{% block content %}
<style>
    
    .col-4{
        display: flex !important; 
        justify-content: space-between !important;
        align-items: center !important;
        flex-direction: column;
    }
    .col-lg-8{
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        
    }

    .recent{
        width: auto;
        height: auto;
    }

    .recentlist{
        width: 100%;
        height: auto;
        display: flex;
        align-items: center;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    #card{
        margin-bottom: 20px !important;
    }

</style>

  <!-- Page content-->
  <div class="container mt-5">
    <div class="row "> 
        <div class="col-lg-12">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                    <!-- Post meta content-->
                    <!-- <div class="text-muted fst-italic mb-2">Posted on {{post.created}} <strong>Modified:</strong> {{post.modified}}</div> -->



                    <a href = "{% url 'profile' post.writer.id %}" style = 'text-decoration: none'>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3"  alt="..." src = "{{post.writer.pictureUrl}}" style = " width: 10%; height: 10%" />
                                <div class="big">
                                    <div class="fw-bold">{{post.writer.name}}</div>
                                    <div class="text-muted">{{post.created}} &middot; 6 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>




                    <!-- Post categories-->
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{post.tag.title}}</a>
                    <!-- <button class="btn btn-danger" href="#!" id = 'followBtn' data-postid= ' {{post.id}} ' >FOLLOW</button> -->
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{post.imageUrl}}" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5" style ='text-align: justify'>
                    <p class="fs-5 mb-4">{{post.body|safe}}.</p>
                    
                </section>
            </article>
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form-->
                        <form class="mb-4" method = 'POST'>
                            {% csrf_token %}
                            <!-- <textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea> -->
                        
                            {{form}}
                            <br>
                        <input type = 'submit' class = 'btn btn-primary' value="Add Comment" style = 'width: 100%'>
                        </form>
                        <!-- Comment with nested comments-->
                        {% for comment in post.comment_set.all %}
                        <div class="d-flex mb-4">
                            <!-- Parent comment-->
                            
                            <div class="flex-shrink-0" style = 'width: 50px; height: 50px'><img class="rounded-circle" style = 'width: 100%; height: 100%' src="{{request.user.profile.picture.url}}" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">{{request.user.profile.name}}</div>
                                {{comment.body}}
                            
                            </div>
                            
                        </div>
                        {% endfor %}
                        <!-- Single comment-->
                        <!-- <div class="d-flex">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                            </div>
                        </div> -->
                    </div>
                </div>
            </section>
        </div>
        
      


       
    </div>

    <div class="row" style="flex-wrap:wrap" style="border: 2px solid black">

        <div class="recent">
            <h3>Recent Posts</h3>
            <div class="recentlist">

                {% for post in posts %}

            
        
                <a href = "{% url 'detail' post.slug %}" style = 'text-decoration: none; color: black'>
                <div class="card" style="width: 15rem;" id="card">
                    <img src=" {{post.imageUrl}} " class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title"> <strong>{{post.title}}</strong> </h5>
                      <p class="card-text">{{post.body | truncatechars:"100" | safe }}</p>
                      
                    </div>
                  </div>
                </a>
                
                  <br>
                  
    
    
            {% endfor %}

            </div>
        </div>
        
       


    </div>


</div>
<script>
    let textarea = document.getElementsByTagName('textarea')
    let label = document.getElementsByTagName('label')
for (let i=0; i<textarea.length; i++){
    textarea[i].classList.add('form-control')
    textarea[i].placeholder = 'Join the discussion and leave a comment!'
    textarea[i].rows = 5
    label[i].style.display = 'none'
    
}
</script>
{% endblock %}

article/templates/article/index.html
{% extends 'base.html' %}
{% block content %}
<style>
    .active{
        background-color: blue;
        color: white;
    }
    .btn-custom{
        border-radius: 20px;
        height: 40px;
        width: auto;
        border: 2px solid lightgray;
        color: grey;
    }
    .btn-custom:hover{
        background-color: lightgray;
        color: black;
    }

    #col{
      margin-bottom: 30px !important;
    }
  
</style>


<header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <!-- <h1 class="display-5 fw-bolder text-white mb-2">A Bootstrap 5 template for modern businesses</h1> -->
                    <h1 class="display-5 fw-bolder text-white mb-2">A Platform designed for modern content creators</h1>
                    <p class="lead fw-normal text-white-50 mb-4">Quickly write and customize compelling and mind blowing articles on Freelance writing, the world’s most popular content creating toolkit!</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'signin' %}">Get Started</a>
                        <a class="btn btn-outline-light btn-lg px-4" href="#allblogs">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src=" img/happy2.jpg " alt="..." /></div>
        </div>
    </div>
</header>

 

  <!-- Blog preview section-->
  <section class="py-5" id = 'allblogs'>
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Top Articles For You</h2>
                    <p class="lead fw-normal text-muted mb-5">Here are articles from our topmost creators. Browse through to find the article you love most.</p>
                </div>
            </div>
        </div>
        <div class = 'container' style = 'display: flex; justify-content: center'>
            {% for tag in tags %}
            <a href  = " {% url 'tag' tag.slug %} ">
            <button type="button" class="btn btn-custom" style = 'margin-right: 10px;'>{{tag.title}}</button></a>
            {% endfor %}
        </div>
        <br>
        <div class="row justify-content-center">
         
            <div class="card-group">
                {% for post in posts %}
                <div class = 'col-12 col-sm-12 col-md-6 col-lg-4' id="col">
                <div class="card" style = "margin-right: 20px">
                <a href = "{% url 'detail' post.slug %}" style="color: black; text-decoration: none">
                  <img src="{{post.imageUrl}}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <small class="text-muted">{{post.tag.title}}</small>
                    <h5 class="card-title"><strong>{{post.title}}</strong></h5>

                    <p>{{post.body|safe|truncatechars:"100"}}</p>
                    {% comment %} <p class="card-text">{{post.body|safe|truncatechars:'150'}}</p> {% endcomment %}
                    {% comment %} <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> {% endcomment %}
                  </div>
                
                </div>
            </a>
        </div>
            
               {% endfor %}
               
              </div>

            <nav aria-label="Page navigation example" style = 'align-self: center' style="margin-top: 100px">
                <ul class="pagination" style = 'justify-content:center;margin-top: 50px'>

                    {% if posts.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{posts.previous_page_number}}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                  {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page=1" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                  {% endif %}

                  {% for page in paginator.page_range %}
                  {% if page == posts.number %}
                  <li class="page-item"><a class="page-link active" href="?page={{page}}"> {{page}} </a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{page}}"> {{page}} </a></li>
                  {% endif %}
                  {% endfor %}
                  {% if posts.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{posts.next_page_number}}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                  {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                  {% endif %}
                </ul>
              </nav>
            
        

    </div> 
</section>

{% endblock %}

article/templates/article/profile.html
{% extends 'base.html' %}
{% block content %}
<style>
    .placeholder{
        width: 300px;
        height: 450px;
        background-color: white;
        box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .placeholderImg{
        width: 200px;
        height: 200px;
        border-radius: 50%;
        border: 2px solid black;
    }
    .placeholderImg img{
        width: 100%;
        height: 100%;
        border-radius: 50%;
    }

</style>

<div class = 'container'>
    <div class = 'row justify-content-center'>
        <div class = 'col-lg-4'>
            <div class='placeholder'>
                <div class = 'placeholderImg'>
                    <img src=''>
                </div>
                <h3></h3>
                <div class ='socials'></div>
                <h4>100 Followers</h4>
            </div>
        </div>

        <div class = 'col-lg-8'>
            <p class ='bio'></p>
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/tag.html
{% extends "base.html" %}
{% block content %}
<br><br>
<div class = "container" >
    <div class = 'row'>
       
        <div class = 'col-12' style = 'display: flex; align-items: center; justify-content: space-around; width: auto' >
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-tags-fill" viewBox="0 0 16 16">
                <path d="M2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2zm3.5 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                <path d="M1.293 7.793A1 1 0 0 1 1 7.086V2a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l.043-.043-7.457-7.457z"/>
              </svg>
            <h3 style = 'margin-left: 20px'> <strong>{{tag.title}}</strong>  </h3>
        </div>
        
    </div>
    <!-- <div class = 'row'>
        <h3> </h3>
    </div> -->
    <br><br>
    <div class = 'row' >
        {% comment %} {% for post in tag.post_set.all %}
       
       
        {% endfor %} {% endcomment %}




        <div class="card-group">
            {% for post in tag.post_set.all %}
            <div class = 'col-12 col-sm-12 col-md-6 col-lg-4'>
            <div class="card" style = "margin-right: 20px">
            <a href = "{% url 'detail' post.slug %}" style="color: black; text-decoration: none">
              <img src="{{post.imageUrl}}" class="card-img-top" alt="...">
              <div class="card-body">
                <small class="text-muted">{{post.tag.title}}</small>
                <h5 class="card-title"><strong>{{post.title}}</strong></h5>
                {% comment %} <p class="card-text">{{post.body|safe|truncatechars:'150'}}</p> {% endcomment %}
                {% comment %} <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> {% endcomment %}
              </div>
            
            </div>
        </a>
    </div>
       
        
           {% endfor %}
           
          </div>


    </div>
</div>
{% endblock %}